# Generated by Django 3.0 on 2020-12-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Usertype',
            new_name='usertype',
        ),
    ]
