# Generated by Django 3.0 on 2020-12-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_seller',
            field=models.ForeignKey(default='35', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
            preserve_default=False,
        ),
    ]
