# Generated by Django 3.0 on 2021-01-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='net_amount',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
